kamg2218/pingpong

backend/myserver/src/config/redirect_url.ts, backend/myserver/src/events/Auth.gateway.ts
=> redirect url : /game & /nickandprofile

backend/Dockerfile, backend/docker-compose.yml, backend/myserver/src/config/ormconfig.ts
1. docker-compose.yaml > db_host 수정
=> db host addr

backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameGateway.service.ts
1. 요청자가 이미 gameroom에 있는지 확인하는 과정 추가
2. 타임아웃되서 match가 삭제된 경우에 요청자에게 알림
=> matchReqeust checkValidate

backend/src/db/repository/Chat/ChatRoom.repository.ts, backend/src/db/repository/User/User.repository.ts, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/chat/chatGateway.service.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameGateway.service.ts, backend/src/socketEvents/online/onlineChatRoom.ts, backend/src/socketEvents/user/userGateway.service.ts
chatroomInfo manager 내용없으면 empty arry로
=> add : chatroom password hashing

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/config/redirect_url.ts, backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/user/user.gateway.ts, backend/src/socketEvents/ws.guard.ts
1. socket guard추가
2. nickname 임시 로그인 추가
3. db 초기 데이터 삽입
=> add guard & add force-login

backend/src/auth/auth.controller.ts, backend/src/auth/auth.module.ts, backend/src/auth/auth.service.ts, backend/src/db/repository/Game/GameHistory.repository.ts, backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameElement/ball.ts, backend/src/socketEvents/game/gameElement/game.ts, backend/src/socketEvents/game/gameElement/player.ts, backend/src/socketEvents/game/gameGateway.service.ts, backend/src/socketEvents/online/onlineManager.ts, backend/src/socketEvents/user/userGateway.service.ts
=> handle socket reconnected during playing game

backend/src/config/const.ts, backend/src/two-factor-authentication/twoFactorAuthentication.service.ts
=> generateQRcode : 생성방식변경

backend/src/user/user.controller.ts
1. 42로그인 후, 2fa 인증이 필요한 상태의 state code 추가 : (2fa)
=> add satate condition : 2fa

backend/src/socketEvents/chat/chat.gateway.ts, backend/src/user/user.service.ts
1. 게임 진행 중인 경우 -> play,  대기 중인 경우 -> waiting
=> add satate condition : waiting

backend/src/auth/auth.service.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts
[수정] waiting room에서 user state 요청시 에러 발생
=> fix : user state

backend/src/config/forty.api.ts, backend/src/config/jwt.config.ts, backend/src/config/ormconfig.ts, backend/src/config/url.ts, backend/src/db/entity/Game/GameRoom.entity.ts, backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/chat/chatGateway.service.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameGateway.service.ts
=> fix : gameroom roomid type

backend/src/socketEvents/game/gameElement/game.ts
1. score 값 삭제
2. startGame 의 left, right 정보에 nickanme, profile 추가
=> fix : draw event

backend/src/main.ts, backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameGateway.service.ts, backend/src/socketEvents/online/onlineChatRoom.ts, backend/src/socketEvents/user/user.gateway.ts
1. friend 요청 & 응답 수정
2. enterGameRoom 이벤트에 isPlayer추가
3. socketio admin페이지 config
=> friend & enterGameRoom

backend/src/db/repository/Game/GameRoom.repository.ts, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/chat/chatGateway.service.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameElement/game.ts, backend/src/socketEvents/game/gameElement/player.ts
1. chatmessage : createdDate -> createDate
2. enterGameRoom : observer가 게임 진행 중 입장할 경우 처리
3. createGameRoom & createChatRoom : hashing 문제 처리
=> fix Event : chatMessage , enterGameRoom, createGameRoom, createChatRoom

backend/src/.env, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/chat/chatGateway.service.ts
1. exitUser응답에 chatid 가 없는 문제 수정
=> Fix Event : exitChatRoom

backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/game/gameElement/ball.ts, backend/src/socketEvents/game/gameElement/game.ts, backend/src/socketEvents/game/gameElement/player.ts, backend/src/socketEvents/game/gameGateway.service.ts, backend/src/socketEvents/online/onlineChatRoom.ts, backend/src/user/user.controller.ts
1. chatmessage에 content , chatid 없는 문제 해결
2. updateChatRoom응답에 chatir 없는 문제 해결
3. 결과 화면에 있는 상태에서 다른 사용자가 들어온 경우 게임시작이 안되는 문제 해결
=> Fix  Event : chatMessage, updateChatRoom, startGame.

backend/src/db/entity/User/User.entity.ts, backend/src/db/repository/Chat/ChatHistoryRepository.ts, backend/src/db/repository/Game/GameMembership.repository.ts, backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameElement/game.ts, backend/src/socketEvents/game/gameGateway.service.ts, backend/src/socketEvents/user/user.gateway.ts, backend/src/socketEvents/user/userGateway.service.ts
1. 대전신청 성공응답에 isPlayer가 없는 문제
2. 관전자만 게임 방에 남아 있는 상황에 게임방이 삭제 되지 않는 문제
=> Fix : match response error, delete room error

backend/src/.env, backend/src/db/entity/Game/GameRoom.entity.ts, backend/src/db/repository/Chat/ChatRoom.repository.ts, backend/src/main.ts, backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/chat/chat.gateway.ts, backend/src/socketEvents/user/user.gateway.ts
1. chatRoomInfo에 max추가
2. deleteFriend 응답 추가
=> Fix : chatRoomInfo, deleteFriend

backend/src/socketEvents/auth/auth.gateway.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameElement/game.ts, backend/src/socketEvents/game/gameElement/player.ts, backend/src/socketEvents/game/gameGateway.service.ts, backend/src/socketEvents/user/user.gateway.ts
1. blockFriend : block된 유저에게 deleteFriend보냄
2. exitGameRoom : 게임방에 관전자만 남아있는 문제 해결.
3. matchRequest : 상대방이 게임방에 있는 경우에도 정상 처리 되는 문제 해결
=> Flx : exitGameRoom, blockFriend

backend/src/socketEvents/game/gameGateway.service.ts
=> Fix: matchRequest

backend/src/db/repository/Game/GameRoom.repository.ts, backend/src/socketEvents/game/game.gateway.ts, backend/src/socketEvents/game/gameElement/ball.ts, backend/src/socketEvents/game/gameElement/game.ts, backend/src/socketEvents/game/gameElement/player.ts, backend/src/socketEvents/game/gameGateway.service.ts
1. 속도3 게임방이 게임시작하면 오류나는 문제 해결
2. 속도에 따라 플레이어의 속도도 상향조정
=> speed up player

backend/src/user/user.controller.ts
user.controller에서 state를 키값으로 리턴으로 변경
=> Fix : user status
